# Generated by Django 2.2.6 on 2019-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=15)),
                ('annio_publicacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
    ]
